 spring.application.name=OnlineLearning

# Configuration database
spring.datasource.url=jdbc:mysql://localhost:3306/elearning
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# Configuration server
server.port=8091

# Cấu hình  Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
