 spring.application.name=OnlineLearning

# Configuration database
spring.datasource.url=jdbc:mysql://localhost:3306/elearning
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.type=com.zaxxer.hikari.HikariDataSource

# Configuration server
server.port=8091

# Cấu hình  Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# cấu hình mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=472bbfd63632da
spring.mail.password=8979025fd3055c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=sandbox.smtp.mailtrap.io

spring.mail.protocol=smtp
spring.mail.test-connection=true

